---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: silex/emacs:27.1-alpine-dev
    commands:
      - emacs -Q --batch -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile init.el
  - name: Slack Notifications
    image: plugins/slack
    channel: dev
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status: failure
