---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: silex/emacs:latest
    commands:
      - emacs -Q --batch -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile init.el
 
  - name: Email Notification
    image: drillster/drone-email
    host:
      from_secret: EMAIL_SMTP_HOST
    username:
      from_secret: EMAIL_USER
    password:
      from_secret: EMAIL_USER
    from:
      from_secret: EMAIL_FROM
    when:
      status: [ changed, failure ]
 
  - name: Slack Notifications
    image: plugins/slack
    channel: dev
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status: failure
