---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: silex/emacs:latest
    commands:
      - emacs -Q --batch -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile init.el
 
  - name: Email Notification
    image: drillster/drone-email
    environment:
      EMAIL_HOST:
        from_secret: EMAIL_SMTP_HOST
      EMAIL_USERNAME:
        from_secret: EMAIL_USER
      EMAIL_PASSWORD:
        from_secret: EMAIL_PASS
    settings:
      from:
        from_secret: EMAIL_FROM
      branch:
        - develop
        - master
    when:
      status: [ changed, failure ]
 
  - name: Slack Notifications
    image: plugins/slack
    channel: dev
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status: failure
