---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: silex/emacs:28.2-ci
    commands:
      - apt install build-essential
      - ./test-startup.sh
 
  - name: Email Notification
    image: drillster/drone-email
    environment:
      EMAIL_HOST:
        from_secret: EMAIL_SMTP_HOST
      EMAIL_USERNAME:
        from_secret: EMAIL_USER
      EMAIL_PASSWORD:
        from_secret: EMAIL_PASS
    settings:
      from:
        from_secret: EMAIL_FROM
      subject: >
        [{{ build.status }}]
        {{ repo.owner }}/{{ repo.name }}
        ({{ commit.branch }})
      body: >
        Build number: # {{ build.number }}
        Build link: {{ build.link }}
        Build started: {{ build.started }}
        Build ended: {{ build.finished }}
        Commit author: {{ commit.author.name }}
        Commit message: {{ commit.message }}
        Commit branch: {{ commit.branch }}
        Commit link: {{ commit.link }}
      branch:
        - develop
        - master
    when:
      status: [ changed, failure ]
 
  - name: Slack Notifications
    image: plugins/slack
    channel: dev
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status: failure
