---
name: Test Emacs Config

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - snapshot
        include:
          - os: [macos-latest, windows-latest]
            emacs_version: 28.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Emacs
        uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Check startup
        uses: actions/checkout@v2
        run: ./test-startup.sh
