---
name: Emacs Config

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}